name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  build:
    runs-on: self-hosted  # Use 'self-hosted' to run on your own server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/nginx:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

      - name: Log out from Docker
        run: docker logout ghcr.io

